### PR TITLE
Implement server features detection.

### PR DESCRIPTION
**Pull request by YoEight**

### CODE REVIEW

**Review by thefringeninja — COMMENTED** [review]
For batch append, the code checks if it's specifically supported but for ps to all it's only asking if the server has implemented server features. Is this correct?

**Review by George-Payne — APPROVED** [review]
Are these additions to make it compile with the new protos, or were they accidentally included?

**Comment by YoEight** [comment]
@thefringeninja Yes

**Comment by YoEight** [comment]
@George-Payne In the beginning I took all the protos from the server. For simplicity sake, I'm willing to discard those and add new proto generation in a separate PR.

**Review by George-Payne — APPROVED** [review]

**Review by thefringeninja — APPROVED** [review]

**Pull request merged**
